### ISSUE TITLE
Getting there

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#11]
Getting there

198 Perimeter Rd, Greenville, SC 29605
Use the above address to navigate to the event location. Parking, start/finish line, on-site registration, packet pickup, and the mandatory safety meeting will be held at this address.
On-site parking will be available. Note: some parking will be in grass - plan accordingly for putting on skates. Surrounding roads will be available for warming up, but please keep an eye out for traffic.
Staying in Greenville
Hotel Deals:
// INSERT HOTEL INFORMATION //
Flying to Greenville
Fly in to the Greenville-Spartanburg International (GSP) airport. The airport is approximately X from the local hotels.
Things to Do in Greenville
Check out our local partners!
// INSERT LOCAL PARTNERS //
Stay in town on Sunday to join us for a fun social skate on the scenic Swamp Rabbit Trail!

**Comment by whereareweskating** [comment]
The copy adjustments I made have not been addressed

**Comment by Abdeboskey** [comment]
Can you be more specific? on my end, I am seeing these all addressed. They may not have been pushed to deployment yet.

**Comment by Abdeboskey** [comment]
Ahh, yes, I replaced "Mandatory Safety Meeting" with "all race operations". I support your safety mission, but I don't think that needs to be explicit here.
