### ISSUE TITLE
Race Info - Relay Info

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#118]
Teams may be comprised of 2, 3, or 4 skaters
Teams may be comprised of same or mixed genders
Teams may be comprised of same or mixed discipline
Junior Teams may be comprised of the same options above, with the added age registration of 14 years or younger.

**Comment by Abdeboskey** [comment]
I changed this to "Junior Team members must be 14 years old or younger" to fit with the length formatting of the other bullet points. I think it's pretty clear that the above points apply to all teams.
