### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#122]
Remove # from Bib column

Adjust Lap 1 - Lap 4 so they are consistent, and don't have the number under Lap.

Can we bold the relay team names and leave the members standard font? 

I would like to add a Country column to future proof this for when we get international representation.

**Comment by Abdeboskey** [comment]
2nd request is no line breaks

**Comment by Abdeboskey** [comment]
@whereareweskating the Lap Num inconsistency is a screen size issue, I'm not sure there's a way to make it not have a line break on smaller screens. Regarding country column, in the current solution for results these tables are generated based on the CSV files that we created, so for next time let's make sure to add a country column - the program will do the rest.

Working on a solution for making relay team names **bold**

**Comment by Abdeboskey** [comment]
Due to the nature of the generative solution for these tables, It's proving to be very challenging to make the team names bold. I'm gonna submit the fix for these other issues and make a new issue for Relay team formatting @whereareweskating
