### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#125]
The final paragraph has not been updated.  It should read:

"We’re proud to offer this outdoor inline & roller skating race in Greenville. We couldn’t do any of this without you, so thank you for joining us on this journey. We look forward to seeing you at the start line!"

**Comment by Abdeboskey** [comment]
Thanks for catching this @whereareweskating ! What if we have it say `We look forward to seeing you at the start line on Saturday, May 18th 2024!`

**Comment by Abdeboskey** [comment]
Also, for further copy updates, it would be really helpful to surround the parts that need to change with backticks, which makes them look like `this` on github. Github's text input boxes use a formatting language called Markdown to style text - the backticks are just one of many markdown formatting tricks.

**Comment by whereareweskating** [comment]
> Thanks for catching this @whereareweskating ! What if we have it say `We look forward to seeing you at the start line on Saturday, May 18th 2024!`

I would like to future proof this so we don't have to change it every year.

**Comment by whereareweskating** [comment]
> Also, for further copy updates, it would be really helpful to surround the parts that need to change with backticks, which makes them look like `this` on github. Github's text input boxes use a formatting language called Markdown to style text - the backticks are just one of many markdown formatting tricks.

I would like to learn how to/gain access to make copy updates.

**Comment by Abdeboskey** [comment]
Cool! I'd love to help you learn how to do that 🤓
