### ISSUE TITLE
Moreathon description 

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#15]
When a marathon just isn’t enough anymore, we offer you the Moreathon!

4 laps/ 28.8 miles

**Comment by Abdeboskey** [comment]
You don't like "take on the full frontal reaper"?

**Comment by whereareweskating** [comment]
I don’t like the health warning. We should supply the specifics of the race, and they can decide if their heart can manage.

**Comment by Abdeboskey** [comment]
I was mostly being humorous, and I agree.
