### ISSUE TITLE
©2023 Carolina Reaper Road Race

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#17]
How do we copyright this properly to legitimize the use of this symbol?

**Comment by Abdeboskey** [comment]
according to [this source](https://www.firstwriter.com/copyright/symbol.shtml):

> You can place the copyright symbol on any original piece of work you have created. However, it is important to note that adding the copyright symbol does not enhance your work's protection in any way. You are merely making a statement that you claim to own the copyright. In order to be able to prove your ownership, you should consider [registering your copyright](https://www.copyrightregistrationservice.com/register), which you can do online through the Intellectual Property Rights Office via their [Copyright Registration Service](https://www.copyrightregistrationservice.com/).

**Comment by thezuver** [comment]
It's $60 for 4 years, if we want to get wild about it:
https://www.copyrightregistrationservice.com/help/charges.shtml

I don't think it's necessary personally.
