### ISSUE TITLE
Race Info: Link Colors & Click Issue

### ISSUE THREAD

**Issue by thezuver** [Abdeboskey/Reaper-Road-Race#28]
Can we make the link colors a burnt orange or red, something that matches the color scheme?
PS the color scheme is AMAZING at the website is looking so good, so professional, so high quality. Loving the layout and visual changes. I digress.

Also - when I click on the link, it takes me right to the section, but the page header pops down so I can't read the section header - is there any way to change that?
PS Love the disappearing header feature - it's working great everywhere else.

**Comment by Abdeboskey** [comment]
Thank you! I appreciate the hype. 100% on changing the link colors.

I have noticed this issue too, I had a hackey workaround for a moment but I changed it up. good catch, I'll figure out how to fix this.
