### ISSUE TITLE
Add Social Media Links

### ISSUE THREAD

**Issue by Abdeboskey** [Abdeboskey/Reaper-Road-Race#32]
Add Links on contact page, and in footer for:
[Strava](https://www.strava.com/clubs/1121972)
[Insta](https://www.instagram.com/reaperroadrace/)
[FB](https://www.facebook.com/reaperroadrace)

**Comment by FredmanOwen** [comment]
Am super happy don't have to bother about recovering or been hacked finally found a man that does everything and anything hack, spy or recover any social media account like he did mine. bohdanbohdan93 @ mail . ru hope he doesn't get offended i let out his contact address though
