### ISSUE TITLE
Relay Info

### ISSUE THREAD

**Issue by Abdeboskey** [Abdeboskey/Reaper-Road-Race#45]
- [x] Finalize team registration instructions 
- [x] Remove info on Relay Zone, (This should be a registration email thing, not a website thing.

**Comment by Abdeboskey** [comment]
I'm not sure what our finalized team registration instructions are here... @whereareweskating did you have any further insight on this?

**Comment by whereareweskating** [comment]
You can change it to the following:

The team captain will register for the whole team, however each member will need to sign a waiver. The other team members will be sent an email with a link to fill out the waiver.
