### ISSUE TITLE
Home Opening Paragraph

### ISSUE THREAD

**Issue by Abdeboskey** [Abdeboskey/Reaper-Road-Race#53]
Come up with a better tagline

Add "presented by Where Are We Skating"

Include some SEO keywords... `inline speed skating` `quad skating` or `roller skating`

**Comment by Abdeboskey** [comment]
Could say `Brought to you by...` instead of "presented by".
or `a Where Are We Skating production`

**Comment by whereareweskating** [comment]
Take 1. (tagline at the end is horrible)

Join Where Are We Skating’s first official event on Saturday June 10th, 2023, the first annual Carolina Reaper Road Race in Greenville, SC. Line up at the start with your friends in your inline skates or roller skates, for an exciting and challenging race on a smooth course.

Read on for more info about the race, the course, where to stay, and what to do in Greenville during the race weekend. Let’s get reapy to rollble!

**Comment by whereareweskating** [comment]
Take 2

Join Where Are We Skating’s inaugural event on Saturday June 10th, 2023, the first annual Carolina Reaper Road Race in Greenville, SC. Line up at the start with your friends in your inline skates or roller skates, for an exciting and challenging race destined to become a southern classic.

Read on for more info about the race, where to stay, and what else to do in Greenville during the event weekend. Greenville’s the place for your new favorite race!

**Comment by whereareweskating** [comment]
Take 3

Join Where Are We Skating’s inaugural event on Saturday June 10th, 2023, the first annual Carolina Reaper Road Race in Greenville, SC. Whether you and your friends line up at the start wearing inline skates or roller skates, this will be an exciting and challenging race destined to become a southern classic.

Read on for more info about the race, where to stay, and what else to do in Greenville during the event weekend. Greenville’s the place for your new favorite race!

**Comment by Abdeboskey** [comment]
What about:
"Whether you're a fan of inline skates, roller skates, skating solo, or skating with your friends, this will be an exciting and challenging race for all - destined to become a southern classic."

I also think we could do without the final tagline, it works well ending with the "Read on..." sentence that will include navigation links to those pages.

**Comment by Abdeboskey** [comment]
And I think that sentence might read:
"Read on for more info about [the race](url), [travel & accommodations](url), and how to [get in touch](url) with any additional questions."

**Comment by whereareweskating** [comment]
Take 4

Join Where Are We Skating’s inaugural event on Saturday June 10th, 2023, the first annual Carolina Reaper Road Race in Greenville, SC. Whether you're a fan of inline skates, roller skates, skating solo, or skating with your friends, this will be an exciting and challenging race that’s destined to become a southern classic.

Read on for more info about [the race](https://github.com/Abdeboskey/Reaper-Road-Race/issues/url), [travel & accommodations](https://github.com/Abdeboskey/Reaper-Road-Race/issues/url), and how to [reach out](https://github.com/Abdeboskey/Reaper-Road-Race/issues/url) with any additional questions.

**Comment by Abdeboskey** [comment]
I like it. I felt the "for all" waved the inclusion/accessibility flag a little bit, but this works. Also, just curious why you like `reach out` instead of `get in touch`?

**Comment by whereareweskating** [comment]
I think I want something other than reach out or get in touch, but it hasn’t come to me yet. If nothing else, reach out is less characters. 😂

**Comment by Abdeboskey** [comment]
lol this is too obvious but what if it was "...and how to `contact us` with any additional questions"

**Comment by whereareweskating** [comment]
Contact us works for me
