### ISSUE TITLE
Logo Font experiment

### ISSUE THREAD

**Issue by Abdeboskey** [Abdeboskey/Reaper-Road-Race#55]
Try the basic outline version of the font for the date in the hero logo.

**Comment by Abdeboskey** [comment]
Here are the two fonts for comparison - I love the version with the gradient lines but I feel like the basic outline version is a little cleaner. Having a hard time telling which is best. @whereareweskating @thezuver would love your thoughts here.

A)
![Screenshot 2023-04-13 at 2 01 08 PM](https://user-images.githubusercontent.com/61372592/231870289-fa5bd49a-b930-4751-bbdc-96c256508129.png)

B)
![Screenshot 2023-04-13 at 2 01 26 PM](https://user-images.githubusercontent.com/61372592/231870337-a78368a3-a664-4fa4-a3f6-bab3e5c996a8.png)

**Comment by whereareweskating** [comment]
I like option A better

**Comment by Abdeboskey** [comment]
Out of context, I do too. But the more I scroll around on the home page the more I think option B is a bit cleaner and more in line with the rest of the styling. I'm gonna push this version to deployment, play around with it and lemme know what you think. We can always switch it back, you know how much I love the gradient lines.

**Comment by whereareweskating** [comment]
That works for me. I trust your styling alignment.
