### ISSUE TITLE
Email link

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#61]
Make the email address in the Contacts section a mailto link.

**Comment by Abdeboskey** [comment]
I know this is a common practice so I'm down... but personally, I don't like how mailto links open your operating system's email management (instead of gmail or something). But I agree, it's the way to do it.

**Comment by Abdeboskey** [comment]
Ultimately, I want to build a contact form that just sends us an email. For the purposes of getting this up and running, Let's use the mailto link for now but I'll make a separate issue for building a contact form.

**Comment by whereareweskating** [comment]
I also agree and don’t like that it opens up the default mail management, and the contact form is a better solution for the future.
