### ISSUE TITLE
Race Info link on bottom of home page

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#62]
Doesn’t bring you to the top of the race info page

**Comment by whereareweskating** [comment]
Also, the Getting There link at the bottom does the same thing on the race info page

**Comment by Abdeboskey** [comment]
Totally, this is addressed in another issue, we can delete this one 😊

**Comment by Abdeboskey** [comment]
Specifically, I think the work in issue #34 will fix this.
