### ISSUE TITLE
Course info

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#66]
Do we remove “(see diagram below for more info on the relay zone).” from the Course Info on the Race Info page, or do we add the image from the Event Location section on the Getting There page to the Relay Info section on the Race Info page?

**Comment by Abdeboskey** [comment]
Thanks for catching this, I think you and I discussed removing that sentence and only showing the site map on the "getting there" page, and instead including a more detailed "relay zone" diagram in the follow up packet.

I'll get it outta there.
