### ISSUE TITLE
Swamp Rabbit Social 

### ISSUE THREAD

**Issue by whereareweskating** [Abdeboskey/Reaper-Road-Race#69]
Determine “Exact details TBD.” and figure out how/where it will live on the site. Separate page, or a large card with time, location, and distance?

**Comment by Abdeboskey** [comment]
Stay in town on sunday for a social skate on the scenic Swamp Rabbit trail. Meet up at [Unity Park](https://unityparkgreenville.com/1843/Unity-Park) at 9:30 am, and roll out at 10:00 am for a fun out-and-back skate (mileage will be determined by the appetite of those who show up!). We’ll meet back at the start after for lunch and some good ol' fashioned socializing.

**Comment by whereareweskating** [comment]
Stay in town on Sunday for a social skate on the scenic Swamp Rabbit trail. We will meet up at [Unity Park](https://unityparkgreenville.com/1843/Unity-Park) starting at 9:30 am, and we will all roll out at 10:00 am for a fun out-and-back skate. Depending on the enthusiasm of the group, we can feed up to 20 miles to those with larger appetites, and the skaters with a more relaxed pace can head back early and only rack up 5 miles. We’ll have multiple group leads to facilitate the group’s needs. We will all meet back at the start for lunch and some good ol' fashioned socializing.

**Comment by Abdeboskey** [comment]
Stay in town on Sunday for a social skate on the scenic Swamp Rabbit trail. We will meet up at [Unity Park](https://unityparkgreenville.com/1843/Unity-Park) starting at 9:30 am, and we will all roll out at 10:00 am for a fun out-and-back skate. Mileage will range from 5-20 depending on who shows up. We will all meet back at the start for lunch and some good ol' fashioned socializing.
